force-app/main/default/objects/Email_Tracking__c/Email_Tracking__c.object-meta.xml
<CustomObject>
    <label>Email Tracking</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Email Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Tracking__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Id</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Email Tracking</relationshipLabel>
    <relationshipName>Email_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_Tracking__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Id</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Email Tracking</relationshipLabel>
    <relationshipName>Email_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email_Tracking__c/fields/Next_Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_up_Date__c</fullName>
    <label>Next Follow up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Email_Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Campaign Email Sent</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>1st Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>2nd Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>3rd Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>4th Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>5th Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>6th Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>7th Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>8th Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>9th Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>10th Follow-Up Sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
                <isActive>false</isActive>
                <label>Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Tracking__c/fields/Thread_ID__c.field-meta.xml
<CustomField>
    <fullName>Thread_ID__c</fullName>
    <label>Thread ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CheckEmailReplies.cls
global class CheckEmailReplies implements Schedulable {
    global void execute(SchedulableContext ctx) {
        // Collect all Thread IDs to check
        List<Email_Tracking__c> sentEmails = [
            SELECT Id, Status__c,Lead_Id__c,Campaign_Id__c,Next_Follow_up_Date__c, Recipient_Email__c, Thread_ID__c 
            FROM Email_Tracking__c 
            WHERE Status__c != 'Replied' AND Next_Follow_up_Date__c <= :System.Now() LIMIT 90
        ];
        
        // Extract thread IDs to check
        //Set<String> threadIds = new Set<String>();      // Instead of set , we will use Map<String,String> for (ThreadId,Status)
        Map<String,String> threadIdStatusMap = new Map<String,String>();
        for (Email_Tracking__c email : sentEmails) {
            if (String.isNotBlank(email.Thread_ID__c)) {
                //threadIds.add(email.Thread_ID__c);          // need to use map of put ThreadId, Status   

                threadIdStatusMap.put(email.Thread_ID__c, email.Status__c);
            }
        }
        
        // Start the asynchronous process
        if (!threadIdStatusMap.isEmpty()) {
            // GmailThreadCheck.checkGmailThreads(threadIds);   // call with  params but  Map(tId,Status)
            GmailThreadCheck.checkGmailThreads(threadIdStatusMap);
        }
    }
}